# syntax=docker/dockerfile:1.4
# FROM --platform=$BUILDPLATFORM python:3.10-alpine AS builder
FROM python:3.8-slim-buster AS builder

WORKDIR /app

COPY requirements.txt /app
RUN apk --update add bash nano \
    pip3 install -r requirements.txt

COPY . /app

ENTRYPOINT ["python3"]
CMD ["-m", "flask", "run", "--host=0.0.0.0"]

FROM builder as dev-envs

RUN <<EOF
apk update
apk add git
EOF

RUN <<EOF
addgroup -S docker
adduser -S --shell /bin/bash --ingroup docker
EOF



ENTRYPOINT ["top", "-b"]