openapi: "3.0.0"
servers:
  - url: "http://localhost:6005"
tags:
  - name: This is SwaggerUI for database server
paths:
  /get-all-table:
    get:
      summary: Retrieve all table names
      description: Endpoint to retrieve all table names from the database.
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
